# Generated by Django 4.1 on 2022-09-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_rename_imdb_ration_film_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkoweInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(6, 'Animacja'), (7, 'Biograficzny'), (4, 'Dramat'), (2, 'Komedia'), (3, 'Sci-Fi'), (1, 'Horror'), (0, 'Inne'), (5, 'Fantazy')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='dodatkowe_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.dodatkoweinfo'),
        ),
    ]
