# Generated by Django 4.1 on 2022-09-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0005_dodatkoweinfo_film_dodatkowe_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-Fi'), (6, 'Animacja'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia'), (7, 'Biograficzny'), (5, 'Fantazy'), (4, 'Dramat')], default=0),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmyweb.film')),
            ],
        ),
    ]
