# Generated by Django 4.1 on 2022-09-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_alter_dodatkoweinfo_gatunek_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Fantazy'), (2, 'Komedia'), (1, 'Horror'), (3, 'Sci-Fi'), (0, 'Inne'), (7, 'Biograficzny'), (6, 'Animacja'), (4, 'Dramat')], default=0),
        ),
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='filmyweb.film')),
            ],
        ),
    ]
